-- Módulo de rutas por municipio - Agua Clara La Muralla
-- Ejecutar una sola vez en Supabase > SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.rutas (
    id uuid primary key default gen_random_uuid(),
    numero bigint generated by default as identity unique,
    nombre text not null,
    municipio text not null,
    dia_semana smallint not null check (dia_semana between 0 and 6),
    latitud numeric not null,
    longitud numeric not null,
    usuario_id uuid references auth.users(id) on delete set null,
    activo boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists public.ruta_clientes (
    id uuid primary key default gen_random_uuid(),
    ruta_id uuid not null references public.rutas(id) on delete cascade,
    cliente_id uuid not null references public.clientes(id) on delete cascade,
    orden integer not null default 0,
    created_at timestamptz not null default now(),
    unique(ruta_id, cliente_id)
);

create table if not exists public.ruta_jornadas (
    id uuid primary key default gen_random_uuid(),
    ruta_id uuid not null references public.rutas(id) on delete cascade,
    fecha date not null default current_date,
    usuario_id uuid not null references auth.users(id),
    estado text not null default 'iniciada'
        check (estado in ('iniciada','finalizada')),
    iniciada_at timestamptz not null default now(),
    finalizada_at timestamptz,
    unique(ruta_id, fecha)
);

create table if not exists public.ruta_visitas (
    id uuid primary key default gen_random_uuid(),
    jornada_id uuid not null references public.ruta_jornadas(id) on delete cascade,
    cliente_id uuid not null references public.clientes(id) on delete cascade,
    orden integer not null default 0,
    estado text not null default 'pendiente'
        check (estado in ('pendiente','visitado','entregado')),
    observacion text,
    visitado_at timestamptz,
    visitado_por uuid references auth.users(id),
    created_at timestamptz not null default now(),
    unique(jornada_id, cliente_id)
);

create index if not exists rutas_dia_activo_idx
    on public.rutas(dia_semana, activo);
create index if not exists ruta_clientes_ruta_idx
    on public.ruta_clientes(ruta_id, orden);
create index if not exists ruta_visitas_jornada_idx
    on public.ruta_visitas(jornada_id, estado);

create or replace function public.es_administrador()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
    select exists (
        select 1 from public.usuarios
        where id = auth.uid() and rol = 'administrador'
    );
$$;

alter table public.rutas enable row level security;
alter table public.ruta_clientes enable row level security;
alter table public.ruta_jornadas enable row level security;
alter table public.ruta_visitas enable row level security;

drop policy if exists "rutas_select_autenticados" on public.rutas;
create policy "rutas_select_autenticados" on public.rutas
for select to authenticated using (true);

drop policy if exists "rutas_admin_escritura" on public.rutas;
create policy "rutas_admin_escritura" on public.rutas
for all to authenticated using (public.es_administrador())
with check (public.es_administrador());

drop policy if exists "ruta_clientes_select_autenticados" on public.ruta_clientes;
create policy "ruta_clientes_select_autenticados" on public.ruta_clientes
for select to authenticated using (true);

drop policy if exists "ruta_clientes_admin_escritura" on public.ruta_clientes;
create policy "ruta_clientes_admin_escritura" on public.ruta_clientes
for all to authenticated using (public.es_administrador())
with check (public.es_administrador());

drop policy if exists "jornadas_select_propias_o_admin" on public.ruta_jornadas;
create policy "jornadas_select_propias_o_admin" on public.ruta_jornadas
for select to authenticated
using (usuario_id = auth.uid() or public.es_administrador());

drop policy if exists "jornadas_insert_propias_o_admin" on public.ruta_jornadas;
create policy "jornadas_insert_propias_o_admin" on public.ruta_jornadas
for insert to authenticated
with check (usuario_id = auth.uid() or public.es_administrador());

drop policy if exists "jornadas_update_propias_o_admin" on public.ruta_jornadas;
create policy "jornadas_update_propias_o_admin" on public.ruta_jornadas
for update to authenticated
using (usuario_id = auth.uid() or public.es_administrador())
with check (usuario_id = auth.uid() or public.es_administrador());

drop policy if exists "visitas_select_propias_o_admin" on public.ruta_visitas;
create policy "visitas_select_propias_o_admin" on public.ruta_visitas
for select to authenticated using (
    public.es_administrador() or exists (
        select 1 from public.ruta_jornadas j
        where j.id = jornada_id and j.usuario_id = auth.uid()
    )
);

drop policy if exists "visitas_insert_propias_o_admin" on public.ruta_visitas;
create policy "visitas_insert_propias_o_admin" on public.ruta_visitas
for insert to authenticated with check (
    public.es_administrador() or exists (
        select 1 from public.ruta_jornadas j
        where j.id = jornada_id and j.usuario_id = auth.uid()
    )
);

drop policy if exists "visitas_update_propias_o_admin" on public.ruta_visitas;
create policy "visitas_update_propias_o_admin" on public.ruta_visitas
for update to authenticated using (
    public.es_administrador() or exists (
        select 1 from public.ruta_jornadas j
        where j.id = jornada_id and j.usuario_id = auth.uid()
    )
) with check (
    public.es_administrador() or exists (
        select 1 from public.ruta_jornadas j
        where j.id = jornada_id and j.usuario_id = auth.uid()
    )
);

grant execute on function public.es_administrador() to authenticated;
grant select, insert, update on public.rutas to authenticated;
grant select, insert, update on public.ruta_clientes to authenticated;
grant select, insert, update on public.ruta_jornadas to authenticated;
grant select, insert, update on public.ruta_visitas to authenticated;
grant usage, select on sequence public.rutas_numero_seq to authenticated;
